# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xup/embedded/2015_2_zynq_labs/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_nco_0_0/ip_design_nco_0_0.xci
# IP: The module: 'ip_design_nco_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/embedded/2015_2_zynq_labs/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_nco_0_0/constraints/nco_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_nco_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/xup/embedded/2015_2_zynq_labs/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_nco_0_0/ip_design_nco_0_0.xci
# IP: The module: 'ip_design_nco_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/embedded/2015_2_zynq_labs/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_nco_0_0/constraints/nco_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_nco_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
